# Generated by Django 4.0.5 on 2023-03-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_joinrequests'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequests',
            unique_together=set(),
        ),
    ]
