# Generated by Django 4.0.5 on 2023-03-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_joinrequests_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequests',
            unique_together={('user', 'room', 'admin')},
        ),
    ]
